### ISSUE TITLE
Add python notebook downloader 

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/sandpaper#1]
Requires

Convert rmd to Jupiter notebook
https://stackoverflow.com/a/57796157/1087595

**Comment by sabaferdous12** [comment]
Similar to this downloader button

https://docs.sunpy.org/en/stable/generated/gallery/acquiring_data/querying_the_GOES_event_list.html#sphx-glr-download-generated-gallery-acquiring-data-querying-the-goes-event-list-py

**Comment by sabaferdous12** [comment]
We want to keep text and code blocks

**Comment by sabaferdous12** [comment]
Converting from markdown to jupyter notebook requires deleting/removing the outputs

**Comment by sabaferdous12** [comment]
Converting markdown to jupyter notebook works locally and produces ipynb but its not producing any ipynb on GitHub Actions (gh-pages branch - site directory). Hence can not access the notebook. There is no errors while building the pages.

There are some warnings about missing images (Can't figure out what they were)

**Comment by milanmlft** [comment]
Fixed and improved in #30 and #36.
