### ISSUE TITLE
Convert Jupiter notebook to sandpaper (r-markdown)

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/sandpaper#3]
1. try it on an existing notebook 
2. Adding styles/boxes
3. Implement in sandpaper (where in folder structure n code)

 https://rmarkdown.rstudio.com/docs/reference/convert_ipynb.html

**Comment by dpshelio** [comment]
`rmarkdwon:::convert_ipynb` doesn't read title and other tags from the metadata, which it's where we could add the information.

On way to do that is by overwriting their [`ipynb_yaml` function](https://github.com/rstudio/rmarkdown/blob/HEAD/R/jupyter.R#L123).  In a hacky way we can do it as:

```R
nb_file <- "sample.ipynb"

library('rmarkdown')
ipynb_yaml <- function(meta, input) {
  # default title and output format
  res <- list(
    title = paste0('This is mine "', input, '"'),
    output = 'html_document'
  )
  # currently only the `authors` field is supported
  authors <- unlist(lapply(meta$authors, `[[`, 'name'))
  if (length(authors) > 0) res[['author']] <- paste(authors, collapse = ', ')
  gsub('\n+$', '', yaml::as.yaml(res))
}
assignInNamespace("ipynb_yaml", ipynb_yaml, "rmarkdown",)

nb_rmd = rmarkdown:::convert_ipynb(nb_file)
```

And calling this file (`ipynb2Rmd.R`) as:

```bash
Rscript  ipynb2Rmd.R
```

Will show that the output title is not their default. We then need to update the code to read other tags in the metadata.

**Comment by milanmlft** [comment]
This doesn't seem relevant anymore so closing.
