### ISSUE TITLE
Update GHA workflow on private repo

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/sandpaper#75]
"Keeping the GHA workflows and package cache up to date would be a lot easier if you would just make the repos public, because then we could use the automated workflows from sandpaper to keep these files up to date"

Based on your above comment, we discussed the possibility of exploring this on private repos. Can you please check that for automation?

**Comment by milanmlft** [comment]
Looks like `sandpaper`'s automated workflow updates do actually work on private repos. Just needs a little tweaking of the [Access Token](https://carpentries.github.io/sandpaper/articles/automated-pull-requests.html?q=token#creating-a-pat) permissions:

![91753739bdcb474437fa43e9a149e6f0](https://github.com/LearnToDiscover/sandpaper/assets/38256462/4a7a97ba-dbad-4bee-9ef1-d744630caa44)

Will update these for all the L2D repos and then should be good to go.
