### ISSUE TITLE
Create L2D lesson template

### ISSUE THREAD

**Issue by sabaferdous12** [LearnToDiscover/sandpaper#86]
As discussed, we want to create L2D lesson template that is based on l2d branch of sandpaper.

We want to add L2D license.md and T&Cs too..

**Comment by milanmlft** [comment]
Template now available at https://github.com/LearnToDiscover/lesson-template
Feel free to edit contents as you see fit.

**Comment by sabaferdous12** [comment]
@milanmlft are you sure the template is for l2d branch of sandpaper? It doesn't show the L2D logos and other personalisation?

Please correct me if I am misunderstanding this

**Comment by milanmlft** [comment]
@sabaferdous12 You're right, I forgot to specify the `sandpaper` and `varnish` versions to use in the config, so it was using the Carpentries default versions.

Should be fixed now: https://github.com/LearnToDiscover/lesson-template/commit/3188a40c5dbeaa947ba0d42e28970d644c334944
