### ISSUE TITLE
Detach fork and make a standalone `sandpaperL2D` package

### ISSUE THREAD

**Issue by milanmlft** [LearnToDiscover/sandpaper#93]
I think that this fork has diverged enough from https://github.com/carpentries/sandpaper to warrant [detaching it](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork). This would allow us to have our own version numbering, releases, and make it possible for someone to have both the Carpentries and L2D  packages installed at the same time in their local R environment, avoiding confusion.

[We may have to go through GitHub support](https://stackoverflow.com/a/16052845/11801854) to preserver Issues, PRs and other metadata linked to this fork.

**Comment by sabaferdous12** [comment]
Sounds like a best Idea.. On that note, can we create a tidied up new PARENT L2D Organisation from now on as we are massively restructuring assignment templates and lessons as well?

**Comment by milanmlft** [comment]
@sabaferdous12 I don't see why you would want to create a new organisation? Also, that's not really related to this issue/suggestion, so could we have that discussion in a different thread?

**Comment by DrAdamLee** [comment]
> I think that this fork has diverged enough from https://github.com/carpentries/sandpaper to warrant [detaching it](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/detaching-a-fork). This would allow us to have our own version numbering, releases, and make it possible for someone to have both the Carpentries and L2D packages installed at the same time in their local R environment, avoiding confusion.
> 
> [We may have to go through GitHub support](https://stackoverflow.com/a/16052845/11801854) to preserver Issues, PRs and other metadata linked to this fork.

Hi Milan - this sounds like a very sensible idea, and would definitely make things a lot clearer, thank you!

**Comment by milanmlft** [comment]
Discussed this further with @dpshelio and decided against it. Instead we should improve the setup and write some documentation on good practices of how to deal with long-term forks.
